eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/   
   
logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG 
    
spring:
  rabbitmq:
    host: ADMINRG-DD0AIR2
