spring:
  application:
    metadataMap:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}

 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port:  5001

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
  
#zuul:
#  routes:
#    cholla: /cholla/**
#    users: /users/**
    
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000

  routes:
    auth-service:
        path: /uaa/**
        url: http://localhost:5000
        stripPrefix: false
        sensitiveHeaders:

    account-service:
        path: /accounts/**
        serviceId: account-service
        stripPrefix: false
        sensitiveHeaders:

    user-service:
        path: /userservice/**
        serviceId: user-service
        stripPrefix: false
        sensitiveHeaders:
